[project]
name = "objasunit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "~=3.10"
dependencies = [
    "ipython>=8.37.0",
    "jupyter>=1.1.1",
    "pandas>=2.3.3",
    "psychopy>=2025.2.2",
    "scipy>=1.14.1",
]
